---
title: "R Notebook"
output: html_notebook
---

```{r}
data = read_csv("../zdiabetes.csv")
data$sex = NULL
data$age = NULL
#data = sample_n(data, size = 250)
data = scale(data)
```


```{r}
out1 = glmBayes(prog ~  ., data = data, iter = 8000, family = "gaussian", log_lik = TRUE, method = "rjparallel")
out2 = extLASSO(prog ~  ., data = data, iter = 8000, family = "gaussian", log_lik = TRUE, method = "rjparallel")
out3 = bayesEnet(prog ~  ., data = data, iter = 8000, family = "gaussian", log_lik = TRUE, method = "rjparallel")
out4 = Spike(prog ~  ., data = data, iter = 8000, family = "gaussian",  log_lik = TRUE, method = "rjparallel")
out5 = apcLm(prog ~  ., data = data, iter = 8000, family = "gaussian", lambda = 4, log_lik = TRUE, method = "rjparallel")
out6 = apcSpike(prog ~  ., data = data, iter = 8000, family = "gaussian", lambda = 4, log_lik = TRUE, method = "rjparallel")
out7 = apcSpikeHS(prog ~  ., data = data, iter = 8000, family = "gaussian", lambda =  4, log_lik = TRUE, method = "rjparallel")
```


```{r}
model = c("bayesian glm", "extended lasso", "bayesian elastic net","Spike", "apc(lambda=4)", "apcSpike(lambda=4)", "apcSpikeHS(lambda=4)")
IC = as.data.frame(t(Kmisc::dapply(list(out1,out2,out3,out4, out5, out6, out7), function(x) IC(x))))
matplot(IC$`LOO-IC`, xlab = "Model", pch = 18, col = "#1e90ffCC", type = "h", lty = 1, lwd = 5, bty  = "n", ylab = "Leave-One-Out CV Information Criterion")
```



```{r}
post_summary(out1)
post_summary(out2)
post_summary(out3)
post_summary(out4)
post_summary(out5)
post_summary(out6)
post_summary(out7)
```

```{r}
out = glmBayes(prog ~  ., data = data, iter = 4000, family = "student_t", log_lik = FALSE, method = "rjparallel")
post_summary(out)
```


